on:
  push:
    branches:
      - master

jobs:
  build:
    name: build application
    runs-on: ubuntu-latest
    steps:
      - name: set golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go version
          go build -o /execute cmd/main.go
