on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build application
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.17’
        run: |
          go version
          make build
