on:
  push:
    branches:
      - master
    inputs:
      username:
        default: 'john-doe'
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: echo 'this is test1 ' + ${{ inputs.username }}
      - name: Test2
        run: echo 'this is test2'